// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCthE5zaXEm1nHLPyqUZgfph3T4Hw2ksoA',
    appId: '1:377322946455:web:266aee5afb5d81aeca8ed2',
    messagingSenderId: '377322946455',
    projectId: 'vault-key-d0ad4',
    authDomain: 'vault-key-d0ad4.firebaseapp.com',
    storageBucket: 'vault-key-d0ad4.firebasestorage.app',
    measurementId: 'G-37ZDMPEZ8S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFfI9Lv5LzksanUEg6lMeyMsn0GBmHwMY',
    appId: '1:377322946455:android:975cc3c2a62574d5ca8ed2',
    messagingSenderId: '377322946455',
    projectId: 'vault-key-d0ad4',
    storageBucket: 'vault-key-d0ad4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxh7GM-DCn5GZkpr958TSt6Bralw3hBJ8',
    appId: '1:377322946455:ios:741c879a02a44a75ca8ed2',
    messagingSenderId: '377322946455',
    projectId: 'vault-key-d0ad4',
    storageBucket: 'vault-key-d0ad4.firebasestorage.app',
    iosBundleId: 'com.example.vaultKey',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxh7GM-DCn5GZkpr958TSt6Bralw3hBJ8',
    appId: '1:377322946455:ios:741c879a02a44a75ca8ed2',
    messagingSenderId: '377322946455',
    projectId: 'vault-key-d0ad4',
    storageBucket: 'vault-key-d0ad4.firebasestorage.app',
    iosBundleId: 'com.example.vaultKey',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCthE5zaXEm1nHLPyqUZgfph3T4Hw2ksoA',
    appId: '1:377322946455:web:dab2e6d4a838d61eca8ed2',
    messagingSenderId: '377322946455',
    projectId: 'vault-key-d0ad4',
    authDomain: 'vault-key-d0ad4.firebaseapp.com',
    storageBucket: 'vault-key-d0ad4.firebasestorage.app',
    measurementId: 'G-PZ00EYE9L1',
  );
}
